remote_theme: pmarsceill/just-the-docs
search_enabled: false

title: Dynazord
logo: /icon-site.png

aux_links:
  GitHub:
    - https://github.com/someimportantcompany/dynazord
  Some Important Company:
    - https://someimportantcompany.com

back_to_top: true
back_to_top_text: "Back to top"

footer_content: >
  Copyright © 2021 <a href="https://someimportantcompany.com/" target="_blank">Some Important Company</a>.
  <a href="https://github.com/someimportantcompany/dynazord/blob/master/LICENSE" target="_blank">MIT License</a>.
  Dynazord has no affiliation with <a href="https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Introduction.html" target="_blank">DynamoDB</a>.

gh_edit_link: true
gh_edit_link_text: Edit this page on GitHub
gh_edit_repository: https://github.com/someimportantcompany/dynazord
gh_edit_branch: master
gh_edit_source: docs
gh_edit_view_mode: edit
